name: YoutuberPlugin
main: YoutuberPlugin\Main
api: 3.11.1
version: 1.0.0
author: Crow
commands:
DC:
description: "ยง2Unser DC Server"
usage: "/DC"
permission: DC.cmd

permission:
DC.cmd:
default: default
