name: YoutuberPlugin
main: YoutuberPlugin\Main
api: 3.11.3
version: 0.0.1
author: Crow
commands:
DC:
description: "ยง2Unser DC Server"
usage: "/DC"
permission: DC.cmd

permission:
DC.cmd:
default: default
