name: YoutuberPlugin
main: YoutuberPlugin\Main
api: 3.0.0
version: 1.0
author: Crow, skillPhil5235, skillDev5235
commands:
DC:
description: "ยง2Unser DC Server"
permission: dc.cmd

permission:
dc.cmd:
default: op
